CREATE TABLE IF NOT EXISTS public.users
(
    -- This replaces the 'nextval' and manual sequence logic
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
    email character varying(100) NOT NULL,
    password character varying(100),
    reset_token text,
    reset_token_expiry timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    sid character varying NOT NULL,
    sess jsonb NOT NULL,
    expire timestamp(6) with time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (sid)
);

COMMENT ON TABLE public.user_sessions IS 'Table for session data';